DROP DATABASE ImprezzMe;
CREATE DATABASE ImprezzMe;

USE ImprezzMe;
CREATE TABLE Users(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(45) NOT NULL,
email VARCHAR(45),
password VARCHAR(100),
cityId INT
);

CREATE TABLE Token(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
value VARCHAR(100) NOT NULL,
UsersId INT NOT NULL UNIQUE,
FOREIGN KEY(UsersId) REFERENCES Users(id)
);

CREATE TABLE Event(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
description VARCHAR(225),
dateStart DATETIME,
cityId INT NOT NULL
);

CREATE TABLE EventUsers(
UsersId INT NOT NULL,
eventId INT NOT NULL,
FOREIGN KEY(UsersId) REFERENCES Users(id),
FOREIGN KEY(eventId) REFERENCES Event(id)
);

CREATE TABLE City(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE Chat(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
link VARCHAR(85) NOT NULL,
eventId INT NOT NULL,
FOREIGN KEY(eventId) REFERENCES Event(id)
);

CREATE TABLE ChatUserss(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UsersId INT NOT NULL UNIQUE,
chatId INT NOT NULL,
FOREIGN KEY(chatId) REFERENCES Chat(id),
FOREIGN KEY(UsersId) REFERENCES Users(id)
);

CREATE TABLE ChatMessages(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UsersId INT NOT NULL UNIQUE,
chatId INT NOT NULL,
message VARCHAR(255) NOT NULL,
date DATETIME NOT NULL DEFAULT NOW(),
FOREIGN KEY(chatId) REFERENCES Chat(id),
FOREIGN KEY(UsersId) REFERENCES Users(id)
);

ALTER TABLE Users ADD FOREIGN KEY(cityId) REFERENCES City(id);
ALTER TABLE Event ADD FOREIGN KEY(cityId) REFERENCES City(id);