DROP DATABASE ImprezzMe;
CREATE DATABASE ImprezzMe;

USE ImprezzMe;
CREATE TABLE User(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
login VARCHAR(45) NOT NULL,
email VARCHAR(45),
password VARCHAR(100),
cityId INT NOT NULL
);

CREATE TABLE Token(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
value VARCHAR(100) NOT NULL,
userId INT NOT NULL UNIQUE,
FOREIGN KEY(userId) REFERENCES User(id)
);

CREATE TABLE Event(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
description VARCHAR(225),
dateStart DATETIME,
cityId INT NOT NULL
);

CREATE TABLE EventUser(
userId INT NOT NULL,
eventId INT NOT NULL,
FOREIGN KEY(userId) REFERENCES User(id),
FOREIGN KEY(eventId) REFERENCES Event(id)
);

CREATE TABLE City(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE Chat(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
link VARCHAR(85) NOT NULL,
eventId INT NOT NULL,
FOREIGN KEY(eventId) REFERENCES Event(id)
);

CREATE TABLE ChatUsers(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
userId INT NOT NULL UNIQUE,
chatId INT NOT NULL,
FOREIGN KEY(chatId) REFERENCES Chat(id),
FOREIGN KEY(userId) REFERENCES User(id)
);

CREATE TABLE ChatMessages(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
userId INT NOT NULL UNIQUE,
chatId INT NOT NULL,
message VARCHAR(255) NOT NULL,
date DATETIME NOT NULL DEFAULT NOW(),
FOREIGN KEY(chatId) REFERENCES Chat(id),
FOREIGN KEY(userId) REFERENCES User(id)
);

ALTER TABLE User ADD FOREIGN KEY(cityId) REFERENCES City(id);
ALTER TABLE Event ADD FOREIGN KEY(cityId) REFERENCES City(id);